// Standalone migration runner. Usage:
//   DATABASE_URL=... pnpm --filter @learn-shell/server db:migrate
//
// Reads SQL files from ./drizzle generated by `drizzle-kit generate`.

// P1-02: apps/server/.env 真加载 — 必须排第一行, 早于下面对
// process.env.DATABASE_URL 的读取。
import '../load-env';
import { drizzle } from 'drizzle-orm/postgres-js';
import { migrate } from 'drizzle-orm/postgres-js/migrator';
import postgres from 'postgres';
import { redactConnectionString } from '../lib/redact-connection-string';
import { requireDatabaseUrl } from './require-database-url';

// 无缺省: 迁移是不可逆写操作, 忘设 DATABASE_URL 必须拒绝启动而不是猜一个库。
// 排在 '../load-env' 之后——.env 里的值先进 process.env, 再做必填检查。
const connectionString = requireDatabaseUrl('db/migrate');

const migrationClient = postgres(connectionString, { max: 1 });
const db = drizzle(migrationClient);

// 数据不出户三针 (针②): 完整连接串含明文密码——只打 host/port/database。
console.log('[migrate] running migrations against', redactConnectionString(connectionString));

await migrate(db, { migrationsFolder: './drizzle' });

console.log('[migrate] done.');

await migrationClient.end();
